### ISSUE TITLE
Should parseComplex Be Public?

### ISSUE THREAD

**Issue by oleibman** [MarkBaker/PHPComplex#23]
PhpSpreadsheet  Calculation/Engineering.php says of its public parseComplex function: "deprecated 1.12.0 No longer used by internal code. Please use the \Complex\Complex class instead". But the parseComplex function here is private, so the PhpSpreadsheet suggestion isn't valid.

**Comment by MarkBaker** [comment]
The `parseComplex()` method in PhpSpreadsheet was only used for unit tests; and they've already been migrated away from using it; so it no longer serves any purpose in PhpSpreadsheet... but because it was a public method in `/src`, I deprecated it rather than deleting it, just in case any developers in userland were using it for any reason.

The method itself has been modified to use this Complex class to provide the same information, so any userland developer using it should simply replace calls to Calculation\Engineering::parseComplex() should have been able to copy that code to their local code, and change their calls using the PhpSpreadsheet version.

The only code in PhpSpreadsheet that now uses that method is a test to verify that it still returned the correct results when I modified it to work with PHPComplex.

So, no! the `parseComplex()` method in the class here doesn't need to be (and shouldn't) be public.

---

Deprecations should only be removed with a new major release.

My intent is to delete it completely when we release PhpSpreadsheet 2.0 sometime in the next few months, alongside all the Calculation.Function classes that we deprecated last year. Until now, there hasn't been any real justification for a 2.0 release; but the changes that I've been making in the `[CalculationEngine-Array-Formulae-Initial-Work](https://github.com/PHPOffice/PhpSpreadsheet/tree/CalculationEngine-Array-Formulae-Initial-Work)` branch break bc, requiring a new major release; but add a lot of new functionality to justify that 2.0 release.

I've already created a [2.0 milestone](https://github.com/PHPOffice/PhpSpreadsheet/milestones) with some comments n the changes that I want to see for that major release (and open to suggestions for more).
![image](https://user-images.githubusercontent.com/770298/159120293-b189aa27-3668-45e7-b19e-2f9783592c5f.png)
(you need to click on the `more...`) link to see the full details.

I was planning on creating the `2.0dev` branch after the next release, which is why I've been pushing myself to get so many improvements done over the last few months, in preparation for that split across to `2.0dev`. For a few months, any PRs merged to master will also need merging into `2.0dev` and subsequently `2.0` once it's released (hopefully sometime in May or June); and renaming `master` as `1.0`.

Maintaining two branches for two releases is a bit of extra work, and might need the occasional merge conflict resolution; so I wouldn't want to have the two running parallel for too long... but once 2.0 was released, all development work would be feature branched off 2.0, merged back to 2.0, and then merged to the older 1.0 branch as well. How long for depends on the packagist stats showing uptake of 2.0; but hopefully not beyond the end of the year.

**Comment by oleibman** [comment]
Thanks for the explanation. That's why I asked this in an issue (which I am now closing) rather than a PR.

Looking forward to 2.0.

**Comment by oleibman** [comment]
BTW, I don't think there's any need to drop Open/Libre Office and Gnumeric compatibility modes. I don't think they create a big maintenance burden.
