### ISSUE TITLE
Why autoload.files in composer.json

### ISSUE THREAD

**Issue by meridius** [MarkBaker/PHPComplex#8]
Hello,

I'd just like to ask what is the reason behind having all the files with functions and operations in `autoload.files` section of `composer.json`. 
I'm curious because, as per [Composer docs](https://getcomposer.org/doc/04-schema.md#files), this way autoloading effectively runs all specified files for every request because lazy-loading cannot work, which obviously consumes precious resources.

Have you thought about having the functions encapsulated in classes instead, so lazy-loading could be used?

Thank you

**Comment by MarkBaker** [comment]
Yes, I did think about encapsulating those functions in classes instead, and it would have been a lot easier.
But I made a conscious decision to make the functions available directly as functions, not simply as classes; and providing the invokers in Complex.php if any user (including myself) want to treat them as methods.
Unfortunately, composer only autoloads classes, not functions, unless they are explicitly mapped filenames in the composer.json file.
And if you're running with opcache, then they're only composer loaded on the first request and then accessible in cache.

**Comment by meridius** [comment]
OK, thank you.

**Comment by tiogatours** [comment]
I just want to say I think all functions should be converted to methods on one central class. As your library is used by packages as PHPOffice, your package is used a lot. And the performance penalty is measurable.

Another issue is that php preloading does not have the full benefits. All the function files will always be included, one by one. File I/O is not the strongpoint of PHP, so this will significantly slow a lot of websites.

A first step to improve the performance would be to merge all the functions in one file. But the best would be to have a class with static methods.

I don't really see the benefits of separate functions. Especially if you take the cons into account.

**Comment by MarkBaker** [comment]
You're quite at liberty to fork the library and remove all those functions there. That's your prerogative.

I made a design decision early on; you disagree with that; but with opcaching, there will be negligible performance overhead after the initial load. Even without opcaching, the performance overhead is minimal, and I have yet to see any evidence to tell me otherwise.

**Comment by storeman** [comment]
Forking is nice, but has also the hassle of maintaining... When we are both maintaining the same thing, that's a waste of effort I would say :).

I did some refactoring in a new branch and ran some benchmarks. I've measured a performance gain of about 3-6ms on around 30ms, which is about 10%-20%!

I created a script which only includes the autoloader, just that one line.

On a whole request, one could argue those couple of ms are not noteworthy, but if every project would have this philosophy, the web would be a lot slower ;).

Keep up the good work 👍

**Comment by MarkBaker** [comment]
Comparing the pre-loading of files with never loading them at all is a pretty false dichotomy. You're not considering what an autoloader does at all, or the overhead when it loads a class file when required... that 10-20% performance gain isn't real, because it isn't measuring what happens when one of those files is required without pre-loading. Only including the autoloader in your test is simply testing the preload and registration of the autoloader, not the use of the autoloader while the main script is actually executing.
Measure the difference between pre-loading those files; or not-preloading them, but loading them at required time, in a situation that actually reflects the usage of the code in those files... that would be a more valid comparison.

Also consider why those files are there; that not everybody uses OOP for their coding. Those files allow procedural access to the functions that they provide, or a simplistic functional approach; so removing the files completely would be breaking BC for the library (creating a new 3.0 branch to maintain in addition to the existing 2.0 and 1.x branches); creating an extra 50% maintenance and support work for me; or excluding a group of PHP developers who currently use this library; or forcing them to change their code to use OOP.


And don't have the audacity to accuse me of slowing the web down (especially when you don't even measure performance in a meaningful manner). It doesn't matter how many smileys and thumbs-up you add to your post, because it's extremely insulting.

**Comment by storeman** [comment]
Mark, please let me clearify that I did not mean to insult you in any way. I was just saying that I think we should always aim for optimal performance. I'm just trying to help.

I do understand how autoloading works. Normally autoloading PSR-(0/4) classes are lazy loaded: load the class when it's needed. Autoloading how it is provided by the Complex library, is partly this: for the class. The functions however, are always loaded because they are in the "files" key. If one would need those functions every request, there was no problem, but most of the time I would not need these functions, because the package that needs them (PHPSpreadsheet), is used occasionally.

So I did measure the performance when not-needing the class or functions, which is exactly my point, I need those functions on 0,01% of the requests, but the "files" (functions, not the classes), are always loaded, thus in 100% of the reqeusts.

Also, I did measure a full 100% backwards compatible solution, by combining all functions into one file. PHP is not good at I/O, so always autoloading many files, is why it is "slow". So an easy solution would be: combine all functions into one file and always load this through composer.json autoloading.

Another approach could be: another package with the functions. The base package would be object-oriented, the extra package could provide one (or separate files) for the functions, which call the methods on the Complex-class.
